import { Metadata } from "next";
import { Roboto, EB_Garamond } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// Import Roboto font
const roboto = Roboto({
  variable: "--font-roboto", // Custom CSS variable
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const garamondDisplay = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-garamond-display", // Custom CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${garamondDisplay.variable} antialiased`}
      >
        <Toaster richColors />
        {children}
      </body>
    </html>
  );
}
